#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Kalculadora.Resource", IsApplication=true)]

namespace Kalculadora
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::Kalculadora.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::Kalculadora.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::Kalculadora.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::Kalculadora.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::Kalculadora.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::Kalculadora.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::Kalculadora.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::Kalculadora.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::Kalculadora.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::Kalculadora.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::Kalculadora.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::Kalculadora.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::Kalculadora.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::Kalculadora.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::Kalculadora.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::Kalculadora.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::Kalculadora.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::Kalculadora.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::Kalculadora.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::Kalculadora.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::Kalculadora.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::Kalculadora.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::Kalculadora.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::Kalculadora.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::Kalculadora.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::Kalculadora.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::Kalculadora.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::Kalculadora.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::Kalculadora.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::Kalculadora.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::Kalculadora.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::Kalculadora.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::Kalculadora.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::Kalculadora.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::Kalculadora.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::Kalculadora.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::Kalculadora.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::Kalculadora.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::Kalculadora.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::Kalculadora.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::Kalculadora.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::Kalculadora.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::Kalculadora.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::Kalculadora.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::Kalculadora.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::Kalculadora.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::Kalculadora.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::Kalculadora.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::Kalculadora.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::Kalculadora.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::Kalculadora.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::Kalculadora.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled = global::Kalculadora.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled;
			global::HockeyApp.Resource.String.hockeyapp_error_no_external_storage_permission = global::Kalculadora.Resource.String.hockeyapp_error_no_external_storage_permission;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::Kalculadora.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::Kalculadora.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::Kalculadora.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::Kalculadora.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::Kalculadora.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_added = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_added;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_remove_description = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_remove_description;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_removed = global::Kalculadora.Resource.String.hockeyapp_feedback_attachment_removed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::Kalculadora.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint_required = global::Kalculadora.Resource.String.hockeyapp_feedback_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::Kalculadora.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::Kalculadora.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::Kalculadora.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::Kalculadora.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint_required = global::Kalculadora.Resource.String.hockeyapp_feedback_message_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::Kalculadora.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint_required = global::Kalculadora.Resource.String.hockeyapp_feedback_name_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_new_answer_notification_message = global::Kalculadora.Resource.String.hockeyapp_feedback_new_answer_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_channel = global::Kalculadora.Resource.String.hockeyapp_feedback_notification_channel;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_title = global::Kalculadora.Resource.String.hockeyapp_feedback_notification_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::Kalculadora.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::Kalculadora.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_fail = global::Kalculadora.Resource.String.hockeyapp_feedback_screenshot_fail;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_notification_message = global::Kalculadora.Resource.String.hockeyapp_feedback_screenshot_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::Kalculadora.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::Kalculadora.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::Kalculadora.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::Kalculadora.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::Kalculadora.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::Kalculadora.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sent_toast = global::Kalculadora.Resource.String.hockeyapp_feedback_sent_toast;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::Kalculadora.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint_required = global::Kalculadora.Resource.String.hockeyapp_feedback_subject_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::Kalculadora.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::Kalculadora.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::Kalculadora.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::Kalculadora.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::Kalculadora.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::Kalculadora.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint_required = global::Kalculadora.Resource.String.hockeyapp_login_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::Kalculadora.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::Kalculadora.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::Kalculadora.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::Kalculadora.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint_required = global::Kalculadora.Resource.String.hockeyapp_login_password_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::Kalculadora.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::Kalculadora.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::Kalculadora.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::Kalculadora.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::Kalculadora.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::Kalculadora.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::Kalculadora.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::Kalculadora.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_update_already_installed = global::Kalculadora.Resource.String.hockeyapp_update_already_installed;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::Kalculadora.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::Kalculadora.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::Kalculadora.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::Kalculadora.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::Kalculadora.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_loading = global::Kalculadora.Resource.String.hockeyapp_update_loading;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::Kalculadora.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_newest_version = global::Kalculadora.Resource.String.hockeyapp_update_newest_version;
			global::HockeyApp.Resource.String.hockeyapp_update_no_info = global::Kalculadora.Resource.String.hockeyapp_update_no_info;
			global::HockeyApp.Resource.String.hockeyapp_update_restore = global::Kalculadora.Resource.String.hockeyapp_update_restore;
			global::HockeyApp.Resource.String.hockeyapp_update_title = global::Kalculadora.Resource.String.hockeyapp_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_unknown_size = global::Kalculadora.Resource.String.hockeyapp_update_unknown_size;
			global::HockeyApp.Resource.String.hockeyapp_update_version = global::Kalculadora.Resource.String.hockeyapp_update_version;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::Kalculadora.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::Kalculadora.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::Kalculadora.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::Kalculadora.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::Kalculadora.Resource.Style.HockeyApp_SingleLineInputStyle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000c
			public const int c_azul = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int c_blanco = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int c_gris = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int c_rojo = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int c_rosa = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int hockeyapp_background_header = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hockeyapp_background_light = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hockeyapp_background_white = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hockeyapp_button_background = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hockeyapp_button_background_pressed = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hockeyapp_button_background_selected = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hockeyapp_text_black = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hockeyapp_text_light = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hockeyapp_text_normal = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hockeyapp_text_white = 2131034121;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonClean = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonIgual = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonNumeric = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonOperacion = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hockeyapp_btn_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_content_create = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_content_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_copy_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_cut_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_paste_holo_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_search_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon2 = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int Creditos = 2131230720;
			
			// aapt resource value: 0x7f080032
			public const int btn0 = 2131230770;
			
			// aapt resource value: 0x7f08002d
			public const int btn1 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int btn2 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int btn3 = 2131230767;
			
			// aapt resource value: 0x7f080029
			public const int btn4 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int btn5 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int btn6 = 2131230763;
			
			// aapt resource value: 0x7f080025
			public const int btn7 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int btn8 = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int btn9 = 2131230759;
			
			// aapt resource value: 0x7f080031
			public const int btnCle = 2131230769;
			
			// aapt resource value: 0x7f080028
			public const int btnDiv = 2131230760;
			
			// aapt resource value: 0x7f080035
			public const int btnIgual = 2131230773;
			
			// aapt resource value: 0x7f080034
			public const int btnMas = 2131230772;
			
			// aapt resource value: 0x7f080030
			public const int btnMen = 2131230768;
			
			// aapt resource value: 0x7f08002c
			public const int btnMul = 2131230764;
			
			// aapt resource value: 0x7f080033
			public const int btnPun = 2131230771;
			
			// aapt resource value: 0x7f080013
			public const int button_add_response = 2131230739;
			
			// aapt resource value: 0x7f08000e
			public const int button_attachment = 2131230734;
			
			// aapt resource value: 0x7f080018
			public const int button_login = 2131230744;
			
			// aapt resource value: 0x7f080014
			public const int button_refresh = 2131230740;
			
			// aapt resource value: 0x7f08000f
			public const int button_send = 2131230735;
			
			// aapt resource value: 0x7f08001c
			public const int button_update = 2131230748;
			
			// aapt resource value: 0x7f08000a
			public const int input_email = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int input_message = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int input_name = 2131230729;
			
			// aapt resource value: 0x7f080017
			public const int input_password = 2131230743;
			
			// aapt resource value: 0x7f08000b
			public const int input_subject = 2131230731;
			
			// aapt resource value: 0x7f08001e
			public const int label_author = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int label_date = 2131230751;
			
			// aapt resource value: 0x7f080011
			public const int label_last_updated = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int label_message = 2131230726;
			
			// aapt resource value: 0x7f080020
			public const int label_text = 2131230752;
			
			// aapt resource value: 0x7f08001a
			public const int label_title = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int label_version = 2131230747;
			
			// aapt resource value: 0x7f080022
			public const int linearLayout1 = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int list_attachments = 2131230753;
			
			// aapt resource value: 0x7f080015
			public const int list_feedback_messages = 2131230741;
			
			// aapt resource value: 0x7f080036
			public const int menu_preferences = 2131230774;
			
			// aapt resource value: 0x7f080016
			public const int text_headline = 2131230742;
			
			// aapt resource value: 0x7f080023
			public const int toolbar = 2131230755;
			
			// aapt resource value: 0x7f080001
			public const int toolbarC = 2131230721;
			
			// aapt resource value: 0x7f080024
			public const int txtValores = 2131230756;
			
			// aapt resource value: 0x7f080005
			public const int txvComplemento = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int txvDerechos = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int txvDeveloper = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int txvNombreApp = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int view_header = 2131230745;
			
			// aapt resource value: 0x7f08001d
			public const int web_update_details = 2131230749;
			
			// aapt resource value: 0x7f08000d
			public const int wrapper_attachments = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int wrapper_feedback = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int wrapper_feedback_scroll = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int wrapper_messages = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int wrapper_messages_buttons = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Creditos = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_expiry_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_feedback = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_fragment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_view_feedback_message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int top_menus = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040057
			public const int ApplicationName = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int NombreApp = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int TituloCreditos = 2130968665;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_crash_dialog_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_crash_dialog_negative_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_crash_dialog_neutral_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_crash_dialog_positive_button = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hockeyapp_crash_dialog_title = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_dialog_error_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_dialog_error_title = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_dialog_positive_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_download_failed_dialog_message = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_download_failed_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_error_install_form_unknown_sources_disabled = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_error_no_external_storage_permission = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_error_no_network_message = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_expiry_info_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_expiry_info_title = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_feedback_attach_file = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_feedback_attach_picture = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_feedback_attachment_added = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_feedback_attachment_button_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_feedback_attachment_error = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_attachment_loading = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_attachment_remove_description = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_attachment_removed = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_email_hint = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_email_hint_required = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_last_updated_text = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_message_hint = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_message_hint_required = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_name_hint = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_name_hint_required = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_new_answer_notification_message = 2130968612;
			
			// aapt resource value: 0x7f040055
			public const int hockeyapp_feedback_notification_channel = 2130968661;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_notification_title = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_refresh_button_text = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_response_button_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_screenshot_fail = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_screenshot_notification_message = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_select_file = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_select_picture = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_send_button_text = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_send_generic_error = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_send_network_error = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_feedback_sending_feedback_text = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_feedback_sent_toast = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_feedback_subject_hint = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_feedback_subject_hint_required = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_feedback_title = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_feedback_validate_email_empty = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_feedback_validate_email_error = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_feedback_validate_name_error = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_feedback_validate_subject_error = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_feedback_validate_text_error = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_login_email_hint_required = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_login_headline_text = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_login_headline_text_email_only = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_login_login_button_text = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_login_missing_credentials_toast = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_login_password_hint_required = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_paint_dialog_message = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_paint_dialog_negative_button = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_paint_dialog_neutral_button = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_paint_dialog_positive_button = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_paint_indicator_toast = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_paint_menu_clear = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_paint_menu_save = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_paint_menu_undo = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_update_already_installed = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int hockeyapp_update_button = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int hockeyapp_update_dialog_message = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int hockeyapp_update_dialog_negative_button = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int hockeyapp_update_dialog_positive_button = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int hockeyapp_update_dialog_title = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int hockeyapp_update_loading = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int hockeyapp_update_mandatory_toast = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int hockeyapp_update_newest_version = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int hockeyapp_update_no_info = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int hockeyapp_update_restore = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int hockeyapp_update_title = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int hockeyapp_update_unknown_size = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int hockeyapp_update_version = 2130968660;
			
			// aapt resource value: 0x7f040056
			public const int hockeyapp_update_version_details_label = 2130968662;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04005d
			public const int textComplemento = 2130968669;
			
			// aapt resource value: 0x7f04005a
			public const int textDerechos = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int textDeveloper = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int textNombre = 2130968668;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HockeyApp_ButtonStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int HockeyApp_EditTextStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int HockeyApp_SingleLineInputStyle = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int MyTheme = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int TemaButtonClean = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int TemaButtonCleanlLand = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int TemaButtonIgual = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int TemaButtonIgualLand = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int TemaButtonNumerico = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int TemaButtonNumericoLand = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int TemaButtonOperacion = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int TemaButtonOperacionLand = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
